[project]
name = "vikram"
version = "0.1.0"
description = "Defeating BETAAL's trickery"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbus-python>=1.3.2",
    "plyer>=2.1.0",
    "requests>=2.32.3",
]
